"""create header banner

Revision ID: b38b48c5c0eb
Revises: 38bddea6a315
Create Date: 2023-07-10 22:13:31.641139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38b48c5c0eb'
down_revision = '38bddea6a315'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('header_banners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_start', sa.DateTime(), nullable=True),
    sa.Column('display_end', sa.DateTime(), nullable=True),
    sa.Column('banner_name', sa.String(), nullable=True),
    sa.Column('banner_description', sa.String(), nullable=True),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('redirection_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('header_banners')
    # ### end Alembic commands ###
